---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python3-pip
        state: present
      ignore_errors: yes
    - name: Install docker
      ansible.builtin.dnf:
        name: docker
        state: present
        allowerasing: yes
      ignore_errors: yes  
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
      ignore_errors: yes  
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
      ignore_errors: yes  
    - name: Start the container
      docker_container:
        name: hariapp
        image: "myphqjaipur/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:80:80
